
# 🏆 FUNDING.yml for "LeetCode Journey by Sandeep Kumar"

github: [sandeepkumar3869]
buy_me_a_coffee: sksandy3869
ko_fi: sandeepkumar3869

custom: 
  - "https://leetcode.com/u/SKSANDY2396/"
  - "mailto:sksandy3869@gmail.com"
  - "https://www.paypal.me/8986578410"
  - "upi://pay?pa=sksandy3869-1@oksbi"