# 🏆 FUNDING.yml for "LeetCode Journey by Sandeep Kumar"

github: [sandeepkumar3869]          # GitHub Sponsors (if enabled)
buy_me_a_coffee: sksandy3869        # Buy Me a Coffee profile
ko_fi: sandeepkumar3869             # Ko-fi profile (optional)

# 👇 Custom sponsorship and contact links
custom:
  - "https://leetcode.com/u/SKSANDY2396/"    # LeetCode profile
  - "mailto:sksandy3869@gmail.com"           # Email contact
  - "https://www.paypal.me/8986578410"       # PayPal donation link
  - "upi://pay?pa=sksandy3869-1@oksbi"    # UPI payment link
